const ERROR_TYPES = {
    ERROR_INALID_ARGUMENTS: 400,
    ERROR_DATA: 400,
    ERROR_NOT_FOUND: 404,
    ERROR_UNAUHTORIZED: 401,
    ERROR_FORBIDDEN: 403,
    ERROR_INTERNAL_ERROR: 500
}

export default ERROR_TYPES